### ISSUE TITLE
Hi, can WE share the data set?

### ISSUE THREAD

**Issue by zbdxkzk** [mrazimi99/deep-packet#1]

**Comment by mrazimi99** [comment]
Hi, the dataset is `VPN-nonVPN dataset (ISCXVPN2016)` and you can find it [here](https://www.unb.ca/cic/datasets/vpn.html).

**Comment by k-loud9** [comment]
Hello! I have some question.
When I did it, I found this error popping up. What additional work should I do?
I would appreciate it if you could answer me. I'll wait.
`
#code
import sys
sys.path.append('drive/MyDrive/deep_packet')
from utils import should_omit_packet, PREFIX_TO_APP_ID, PREFIX_TO_TRAFFIC_ID, ID_TO_APP, ID_TO_TRAFFIC`

`
#error
ImportError                              Traceback (most recent call last)
<ipython-input-9-0e0c79a1d913> in <module>()
     36 import sys
     37 sys.path.append('drive/MyDrive/deep_packet')
---> 38 from utils import should_omit_packet, PREFIX_TO_APP_ID, PREFIX_TO_TRAFFIC_ID, ID_TO_APP, ID_TO_TRAFFIC

ImportError: cannot import name 'should_omit_packet' from 'utils' (/usr/local/lib/python3.7/dist-packages/utils/__init__.py)
`
