### ISSUE TITLE
I can't import name 'should_omit_packet' from 'utils' 

### ISSUE THREAD

**Issue by include-seul** [mrazimi99/deep-packet#2]
Hello! I have some question.
When I did it, I found an error in this part.
import sys sys.path.append('drive/MyDrive/deep_packet') from utils import should_omit_packet, PREFIX_TO_APP_ID, PREFIX_TO_TRAFFIC_ID, ID_TO_APP, ID_TO_TRAFFIC

What additional work should I do? I'll attach the error below.
I would appreciate it if you could answer me. I'll wait.

`#error
ImportError Traceback (most recent call last)
in ()
36 import sys
37 sys.path.append('drive/MyDrive/deep_packet')
---> 38 from utils import should_omit_packet, PREFIX_TO_APP_ID, PREFIX_TO_TRAFFIC_ID, ID_TO_APP, ID_TO_TRAFFIC

ImportError: cannot import name 'should_omit_packet' from 'utils' (/usr/local/lib/python3.7/dist-packages/utils/init.py)`

**Comment by mrazimi99** [comment]
Hello, thanks for mentioning the problem. I've just added the utils.py file to the repository.
