### ISSUE TITLE
 found an error in the sentence: from utils import should_ omit_ packet, PREFIX_ TO_ APP_ ID, PREFIX_ TO_ TRAFFIC_ ID, ID_ TO_ APP, ID_ TO_ Traffic. 

### ISSUE THREAD

**Issue by gbw1998** [mrazimi99/deep-packet#3]
Recently, I'm learning the source code of the deep packet you put on GitHub. It's really good. I admire you very much. I found an error in the sentence: from utils import should_ omit_ packet, PREFIX_ TO_ APP_ ID, PREFIX_ TO_ TRAFFIC_ ID, ID_ TO_ APP, ID_ TO_ Traffic. I found that this utils may be your own source code. I wonder if you can send me the source code of utils? Thank you very much and look forward to your reply!

**Comment by mrazimi99** [comment]
Hello, thanks for mentioning the problem. I've just added the utils.py file to the repository.
